### ISSUE TITLE
topspin script crashes if pdflatex variable isn't set

### ISSUE THREAD

**Issue by yongrenjie** [foroozandehgroup/NMR-EsPy#1]
There's also another bug here, if `pdflatex_exe` isn't set during installation then whenever it's called from TopSpin this will crash as `subprocess.Popen` doesn't expect a `None` parameter:

https://github.com/foroozandehgroup/NMR-EsPy/blob/46b56a69a912f011de8920226cb596ed20e75320/nmrespy/app/_topspin.py#L80-L91

Not sure what you prefer to do with it -- I imagine you handle the error downstream if they ask for a PDF (since latex isn't likely to be installed on a typical spectrometer)?

**Comment by 5hulse** [comment]
Cheers for this Jon. I have replaced `pdflatex_exe = None` with `pdflatex = "None"` in the topspin script, and included some processing downstream to deal with it. The GUI is now working in on my Windows installation.

**Comment by yongrenjie** [comment]
closed by 047848e
